config/routes.rb
Jcl::Application.routes.draw do
  root:to => 'books#index'

  resources :donators

  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :donator
end

app/models/donator.rb
class Donator < ActiveRecord::Base
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :category, :donator_id, :published)
    end
end

app/controllers/donators_controller.rb
class DonatorsController < ApplicationController
  before_action :set_donator, only: [:show, :edit, :update, :destroy]

  # GET /donators
  # GET /donators.json
  def index
    @donators = Donator.all
  end

  # GET /donators/1
  # GET /donators/1.json
  def show
  end

  # GET /donators/new
  def new
    @donator = Donator.new
  end

  # GET /donators/1/edit
  def edit
  end

  # POST /donators
  # POST /donators.json
  def create
    @donator = Donator.new(donator_params)

    respond_to do |format|
      if @donator.save
        format.html { redirect_to @donator, notice: 'Donator was successfully created.' }
        format.json { render action: 'show', status: :created, location: @donator }
      else
        format.html { render action: 'new' }
        format.json { render json: @donator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donators/1
  # PATCH/PUT /donators/1.json
  def update
    respond_to do |format|
      if @donator.update(donator_params)
        format.html { redirect_to @donator, notice: 'Donator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @donator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donators/1
  # DELETE /donators/1.json
  def destroy
    @donator.destroy
    respond_to do |format|
      format.html { redirect_to donators_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donator
      @donator = Donator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donator_params
      params.require(:donator).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

 def index
   @books = Book.all
   redirect_to '/books' and return 
  render layout: 'application'
 end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/donators_helper.rb
module DonatorsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :donator_id %><br>
    <%= f.number_field :donator_id %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.date_select :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Donator:</strong>
  <%= @book.donator_id %>
</p>

<p>
  <strong>Published:</strong>
  <%= @book.published %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<section id="JCLibrary">
    <%= image_tag "logo.png" , :class=> "logo" %> 
    <h1>Chicago JC Lending Library</h1>
    <p>A resource for all to bring us together and to bring us forward! The goal of the JC Lending library is to build the JC community by <strong>advancing careers through learning and discussion.</strong> The Lending Library should be a reliable place of valuable resources that are <strong>curated</strong> and proven to be helpful.</p>
    <p>The JC Lending Library is based on donations from you and your peers.</p>
    <p class="nb">*Note: this is not a record meant to show availability.</p>
  </section>
  
  <section id="catalog">
    <h1>Catalog</h1>
    <table class="catalog-sheet">
      <thead>
        <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Category</th>
        <th>Donator</th>
        <th>Donation Date</th>
        <th></th>
        <th></th>
        <th></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.category %></td>
          <td><%= book.donator_id %></td>
          <td><%= book.published %></td>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'New Book', new_book_path %> 
  </section>

  <section id="how-to">
    <h1>How To</h1>
    <p>What is the procedure for checking out and checking in books?</p>
    <p>It is expected that a person donates a book to the library before s/he checks out hir first book. Then, that JC may happily check out and check in books as s/he pleases! :)</p>

    <a href="#donating" class="accordian"><h2>Donating</h2></a>
    <ol id="donating" class="accordian-content">
      <li>Glance at the "List of Desired Books" on the left side of the bookshelf</li>
      <li>Pick one that you would like to contribute! Pro tip: You can ship it directly to the Chicago office</li>
      <li>Don't forget to expense it! You can expense up to $150 of books to TW. The expense code will be under <span class="nb"TW Core Business > External training or books > External training or books > books </span></li>
      <li>Bring the book to the bookcase! Feel free to grab the librarian to help you. Write your name as the donator of the book on the left/front inner cover.</li>
      <li>Gluestick a library pocket onto the right/back inner cover of the book.</li>
      <li>Pick up the book library card and fill out its details of book title and author. Insert the card into the library pocket.</li>
      <li>Lovingly place the book into the bookcase! :) And enjoy the entire bookshelf, now available at your finger tips</li>
    </ol>

    <a href="#checking-out" class="accordian"><h2>Checking Out</h2></a>
    <ol id="checking-out" class="accordian-content">
      <li>Find a book you'll enjoy & open it up</li>
      <li>Find the library card in the pocket placed behind the left cover</li>
      <li>Take out the card and write your name and the current date on the next row</li>
      <li>Place the card in the handy dandy index card box (THE HANDY DANDY) at the top so that the most recent checkout is at the top like a stack! FIFO</li>
      <li>Enjoi your book and read it well, grasshopper!</li>
    </ol>

    <a href="#checking-in" class="accordian"><h2>Checking In</h2></a>
    <ol id="checking-in" class="accordian-content">
      <li> Find the card corresponding to your book in THE HANDY DANDY</li>
      <li>Mark the return date next to the checkout date</li>
      <li><span class="nb">*Gently*</span> slide the card back into the book pocket</li>
      <li>Make peace with the fact that the book is returning home to the JC Lending Libr'’'y</li>
      <li>Place the book back onto its shelf</li>
    </ol>

  </section>

  <section id="contact">
    <h1>Contact</h1>
    <p>You are free to contact the current librarian or anyone on the Chicago beach anytime with any question. These questions can be anything, such as:</p>
    <ul>
      <li>Is this book available?</li>
      <li>What books in X category do you recommend?</li>
      <li>What is your favorite pastry?</li>
    </ul>
    <p class="contact-librarian">Contact the Chicago JC librarian <a href="mailto:ddelrosa@thoughtworks.com">here</a></p>
  </section>

</div>
</body>

</html>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Donator:</strong>
  <%= @book.donator_id %>
</p>

<p>
  <strong>Published:</strong>
  <%= @book.published %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/donators/_form.html.erb
<%= form_for(@donator) do |f| %>
  <% if @donator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donator.errors.count, "error") %> prohibited this donator from being saved:</h2>

      <ul>
      <% @donator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donators/edit.html.erb
<h1>Editing donator</h1>

<%= render 'form' %>

<%= link_to 'Show', @donator %> |
<%= link_to 'Back', donators_path %>

app/views/donators/index.html.erb
<h1>Listing donators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @donators.each do |donator| %>
      <tr>
        <td><%= donator.name %></td>
        <td><%= link_to 'Show', donator %></td>
        <td><%= link_to 'Edit', edit_donator_path(donator) %></td>
        <td><%= link_to 'Destroy', donator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donator', new_donator_path %>

app/views/donators/new.html.erb
<h1>New donator</h1>

<%= render 'form' %>

<%= link_to 'Back', donators_path %>

app/views/donators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donator.name %>
</p>

<%= link_to 'Edit', edit_donator_path(@donator) %> |
<%= link_to 'Back', donators_path %>

app/views/layouts/_navbar.html.erb
  <nav>
    <ul>
      <li><%= link_to "JCLibrary", root_path %></li>
      <li><a href="#catalog">Catalog</a></li>
      <li><a href="#how-to">How To</a></li>
      <li><a href="#contact">Contact</a></li>
      <li><%= link_to "Donators", donators_path %></li>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chicago JC Library</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Raleway:700,300' rel='stylesheet' type='text/css'> <link rel="stylesheet" type="text/css" href="style.css">
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      function filterPath(string) {
      return string
        .replace(/^\//,'')
        .replace(/(index|default).[a-zA-Z]{3,4}$/,'')
        .replace(/\/$/,'');
      }
      var locationPath = filterPath(location.pathname);
      var scrollElem = scrollableElement('html', 'body');

      $('a[href*=#]').each(function() {
        var thisPath = filterPath(this.pathname) || locationPath;
        if (  locationPath == thisPath
        && (location.hostname == this.hostname || !this.hostname)
        && this.hash.replace(/#/,'') ) {
          var $target = $(this.hash), target = this.hash;
          if (target) {
            var targetOffset = $target.offset().top;
            $(this).click(function(event) {
              event.preventDefault();
              $(scrollElem).animate({scrollTop: targetOffset}, 400, function() {
                location.hash = target;
              });
            });
          }
        }
      });

      // use the first element that is "scrollable"
      function scrollableElement(els) {
        for (var i = 0, argLength = arguments.length; i <argLength; i++) {
          var el = arguments[i],
              $scrollElement = $(el);
          if ($scrollElement.scrollTop()> 0) {
            return el;
          } else {
            $scrollElement.scrollTop(1);
            var isScrollable = $scrollElement.scrollTop()> 0;
            $scrollElement.scrollTop(0);
            if (isScrollable) {
              return el;
            }
          }
        }
        return [];
      }

    });
  </script>
</head>

<body>
  <%= render "layouts/navbar" %>
  <div class="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/index.html.erb
 <section id="JCLibrary">
    <%= image_tag "logo.png" , :class=> "logo" %> 
    <h1>Chicago JC Lending Library</h1>
    <p>A resource for all to bring us together and to bring us forward! The goal of the JC Lending library is to build the JC community by <strong>advancing careers through learning and discussion.</strong> The Lending Library should be a reliable place of valuable resources that are <strong>curated</strong> and proven to be helpful.</p>
    <p>The JC Lending Library is based on donations from you and your peers.</p>
    <p class="nb">*Note: this is not a record meant to show availability.</p>
  </section>

  <section id="catalog">
    <%= render "books/show" %>
  </section>

  <section id="how-to">
    <h1>How To</h1>
    <p>What is the procedure for checking out and checking in books?</p>
    <p>It is expected that a person donates a book to the library before s/he checks out hir first book. Then, that JC may happily check out and check in books as s/he pleases! :)</p>

    <a href="#donating" class="accordian"><h2>Donating</h2></a>
    <ol id="donating" class="accordian-content">
      <li>Glance at the "List of Desired Books" on the left side of the bookshelf</li>
      <li>Pick one that you would like to contribute! Pro tip: You can ship it directly to the Chicago office</li>
      <li>Don't forget to expense it! You can expense up to $150 of books to TW. The expense code will be under <span class="nb"TW Core Business > External training or books > External training or books > books </span></li>
      <li>Bring the book to the bookcase! Feel free to grab the librarian to help you. Write your name as the donator of the book on the left/front inner cover.</li>
      <li>Gluestick a library pocket onto the right/back inner cover of the book.</li>
      <li>Pick up the book library card and fill out its details of book title and author. Insert the card into the library pocket.</li>
      <li>Lovingly place the book into the bookcase! :) And enjoy the entire bookshelf, now available at your finger tips</li>
    </ol>

    <a href="#checking-out" class="accordian"><h2>Checking Out</h2></a>
    <ol id="checking-out" class="accordian-content">
      <li>Find a book you'll enjoy & open it up</li>
      <li>Find the library card in the pocket placed behind the left cover</li>
      <li>Take out the card and write your name and the current date on the next row</li>
      <li>Place the card in the handy dandy index card box (THE HANDY DANDY) at the top so that the most recent checkout is at the top like a stack! FIFO</li>
      <li>Enjoi your book and read it well, grasshopper!</li>
    </ol>

    <a href="#checking-in" class="accordian"><h2>Checking In</h2></a>
    <ol id="checking-in" class="accordian-content">
      <li> Find the card corresponding to your book in THE HANDY DANDY</li>
      <li>Mark the return date next to the checkout date</li>
      <li><span class="nb">*Gently*</span> slide the card back into the book pocket</li>
      <li>Make peace with the fact that the book is returning home to the JC Lending Libr'’'y</li>
      <li>Place the book back onto its shelf</li>
    </ol>

  </section>

  <section id="contact">
    <h1>Contact</h1>
    <p>You are free to contact the current librarian or anyone on the Chicago beach anytime with any question. These questions can be anything, such as:</p>
    <ul>
      <li>Is this book available?</li>
      <li>What books in X category do you recommend?</li>
      <li>What is your favorite pastry?</li>
    </ul>
    <p class="contact-librarian">Contact the Chicago JC librarian <a href="mailto:ddelrosa@thoughtworks.com">here</a></p>
  </section>

</div>
</body>

</html>